# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xuxing/projects/cpp_example/linux_unix_programming_manual

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xuxing/projects/cpp_example/linux_unix_programming_manual

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xuxing/projects/cpp_example/linux_unix_programming_manual/CMakeFiles /home/xuxing/projects/cpp_example/linux_unix_programming_manual/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xuxing/projects/cpp_example/linux_unix_programming_manual/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named curreacy_io

# Build rule for target.
curreacy_io: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 curreacy_io
.PHONY : curreacy_io

# fast build rule for target.
curreacy_io/fast:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/build
.PHONY : curreacy_io/fast

lib/copy.o: lib/copy.c.o

.PHONY : lib/copy.o

# target to build an object file
lib/copy.c.o:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/lib/copy.c.o
.PHONY : lib/copy.c.o

lib/copy.i: lib/copy.c.i

.PHONY : lib/copy.i

# target to preprocess a source file
lib/copy.c.i:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/lib/copy.c.i
.PHONY : lib/copy.c.i

lib/copy.s: lib/copy.c.s

.PHONY : lib/copy.s

# target to generate assembly for a file
lib/copy.c.s:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/lib/copy.c.s
.PHONY : lib/copy.c.s

lib/currency_IO_4-1.o: lib/currency_IO_4-1.c.o

.PHONY : lib/currency_IO_4-1.o

# target to build an object file
lib/currency_IO_4-1.c.o:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/lib/currency_IO_4-1.c.o
.PHONY : lib/currency_IO_4-1.c.o

lib/currency_IO_4-1.i: lib/currency_IO_4-1.c.i

.PHONY : lib/currency_IO_4-1.i

# target to preprocess a source file
lib/currency_IO_4-1.c.i:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/lib/currency_IO_4-1.c.i
.PHONY : lib/currency_IO_4-1.c.i

lib/currency_IO_4-1.s: lib/currency_IO_4-1.c.s

.PHONY : lib/currency_IO_4-1.s

# target to generate assembly for a file
lib/currency_IO_4-1.c.s:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/lib/currency_IO_4-1.c.s
.PHONY : lib/currency_IO_4-1.c.s

lib/error_functions.o: lib/error_functions.c.o

.PHONY : lib/error_functions.o

# target to build an object file
lib/error_functions.c.o:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/lib/error_functions.c.o
.PHONY : lib/error_functions.c.o

lib/error_functions.i: lib/error_functions.c.i

.PHONY : lib/error_functions.i

# target to preprocess a source file
lib/error_functions.c.i:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/lib/error_functions.c.i
.PHONY : lib/error_functions.c.i

lib/error_functions.s: lib/error_functions.c.s

.PHONY : lib/error_functions.s

# target to generate assembly for a file
lib/error_functions.c.s:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/lib/error_functions.c.s
.PHONY : lib/error_functions.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/curreacy_io.dir/build.make CMakeFiles/curreacy_io.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... curreacy_io"
	@echo "... edit_cache"
	@echo "... lib/copy.o"
	@echo "... lib/copy.i"
	@echo "... lib/copy.s"
	@echo "... lib/currency_IO_4-1.o"
	@echo "... lib/currency_IO_4-1.i"
	@echo "... lib/currency_IO_4-1.s"
	@echo "... lib/error_functions.o"
	@echo "... lib/error_functions.i"
	@echo "... lib/error_functions.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

